export const projects = [
  {
    title: 'JuKoin',
    description:"Built this real world Web 3.0 project for sending Ethereum using MetaMask",
    image: '/images/jukoin.png',
    tags: ['HTML', 'CSS', 'JavaScript','Solidity','Blockchain'],
    visit: 'https://jukoin.vercel.app/',
    id: 0,
  },
  {
    title: 'JWebDev',
    description: "Using Next.js, GraphCMS, and Github, i built a blog for beginners",
      image: '/images/blog.png',
      tags: ['Next.js', 'GraphCMS'],
    visit: 'https://jwebdev.vercel.app/',
    id: 1,
  },
  {
    title: 'JT-NGO',
    description:"Built this beauty using HTML, CSS and JavaScript",
    image: '/images/ngo.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-ngo.netlify.app/',
    id: 2,
  },
  {
    title: 'JServices',
    description: "Built this fashion template using HTML and CSS only",
      image: '/images/fashion.png',
      tags: ['HTML', 'CSS'],
    visit: 'https://jservices.vercel.app/',
    id: 3,
  },
  {
    title: 'TIC-TAC-TOE',
    description: "This game was built using JavaScript",
    image: '/images/ttt.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-tictactoe.netlify.app/',
    id: 4,
  },
  {
    title: 'Portfolio',
    description: "This was built without using any framework",
    image: '/images/portfolio.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-portfolio1.netlify.app/',
    id: 5,
  },
  {
    title: 'Medical Lab',
    description: "A medical laboratory site",
    image: '/images/stopwatch.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://muelbeth.vercel.app/',
    id: 6,
  },
  {
    title: 'JT-fashion',
    description: "Todo app to prioritize your tasks",
    image: '/images/todo.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-fashion.netlify.app/',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Graduated from the University', },
  { year: 2020, text: 'Further development in web development', },
  { year: 2021, text: 'Built projects', },
];
