export const projects = [
  {
    title: 'JuKoin',
    description:"Built this real world Web 3.0 project for sending Ethereum using MetaMask",
    image: '/images/jukoin.png',
    tags: ['HTML', 'CSS', 'JavaScript','Solidity','Blockchain'],
    visit: 'https://jukoin.vercel.app/',
    id: 0,
  },
  {
    title: 'JWebDev',
    description: "Using Next.js, GraphCMS, and Github, i built a blog for beginners",
      image: '/images/blog.png',
      tags: ['Next.js', 'GraphCMS'],
    visit: 'https://jwebdev.vercel.app/',
    id: 1,
  },
  {
    title: 'Muelbeth',
    description: "A medical laboratory website built with html, CSS and JavaScript",
      image: 'https://muelbeth.vercel.app/assets/img/gallery/gallery-3.jpg',
      tags: ['html', 'css'],
    visit: 'https://muelbeth.vercel.app/',
    id: 2,
  },
{
    title: 'Construction',
    description: "A construction template website built with Html, CSS and JavaScript",
      image: 'https://kibtech.vercel.app/images/blog-4.jpg',
      tags: ['html', 'css'],
    visit: 'https://kibtech.vercel.app/',
    id: 3,
  },
  {
    title: 'JT-NGO',
    description:"Built this beauty using HTML, CSS and JavaScript",
    image: '/images/ngo.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-ngo.netlify.app/',
    id: 4,
  },
  {
    title: 'JServices',
    description: "Built this construction service finder website template using HTML and CSS only",
      image: 'https://kibtech.vercel.app/images/project-1.jpg',
      tags: ['HTML', 'CSS'],
    visit: 'https://jservices.vercel.app/',
    id: 5,
  },
  {
    title: 'TIC-TAC-TOE',
    description: "This game was built using JavaScript",
    image: '/images/ttt.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-tictactoe.netlify.app/',
    id: 6,
  },
  {
    title: 'Portfolio',
    description: "This was built without using any framework",
    image: '/images/portfolio.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-portfolio1.netlify.app/',
    id: 7,
  },
  {
    title: 'Jbusiness-card (still-in-progress)',
    description: "A website to design your digital business card",
    image: 'https://cdn.pixabay.com/photo/2014/08/25/22/53/business-card-427513__480.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jbusinesscard.vercel.app/',
    id: 8,
  },
  {
    title: 'JT-fashion',
    description: "Todo app to prioritize your tasks",
    image: 'https://jt-fashion.netlify.app/css/images/background2.jpg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    visit: 'https://jt-fashion.netlify.app/',
    id: 9,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Graduated from the University', },
  { year: 2020, text: 'Further development in web development', },
  { year: 2021, text: 'Built projects', },
];
